src/database/DatabaseConnector.ts, tests/unit/DatabaseConnector.ts
=> Fix getting DB name from connection URL

CONTRIBUTING.md, README.md, cli/README.md, core/README.md, docker-image/README.md, docs/README.md, docs/define-import-data.md, samples/README.md
=> Add documentation with contribution rules

cli/README.md, cli/src/options.ts, core/README.md, core/src/common/config.ts, core/src/common/types.ts, core/src/database/Database.ts, core/src/index.ts, core/tests/integration/Database.ts, core/tests/integration/seedDatabase.ts, core/tests/unit/config.ts, docker-image/README.md, docker-image/src/index.ts
=> Allow dropping every collection that is being imported

core/src/database/DatabaseConnector.ts
=> Fix deprecation message while data import

cli/bin/seed.js, cli/package-lock.json, cli/package.json, cli/src/index.ts, cli/src/options.ts, samples/example-ts/README.md, samples/example-ts/data/1-categories/categories.ts, samples/example-ts/data/2-posts/posts.ts
=> Enable TypeScript runtime in CLI

README.md, cli/README.md, cli/package-lock.json, cli/package.json, cli/src/index.ts, cli/src/options.ts
=> Support environmental variables in CLI

cli/src/index.ts
=> Catch all errors from command-line-args

cli/README.md, cli/src/options.ts
=> Set input path as default option for CLI

cli/README.md, core/README.md
=> Fix links in Readme files for NPM packages

cli/README.md, cli/bin/seed.js, cli/src/index.ts, cli/src/options.ts, cli/src/types.ts, cli/test/integration/index.ts, docker-image/dev.Dockerfile, docker-image/prod.Dockerfile
=> Add `transpile-only` option for CLI and Docker image

core/src/database/database-connector.ts, core/test/unit/DatabaseConnector.ts
=> Do not print DB connection user credentials in logs

examples/import-data-ts/example/data/2-posts/posts.ts, examples/import-data-ts/example/models/post.ts, examples/import-data-ts/example/package-lock.json, examples/import-data/example/data/2-posts/posts.js, examples/import-data/example/helpers/index.js
From now the examples shows how to make a relation between documents based on references in data import files.
See #75
=> Define relation between post and categories in examples

cli/README.md, cli/src/index.ts, cli/src/options.ts, cli/src/types.ts, cli/test/integration/index.ts, cli/test/unit/options.ts
=> Add ability to disable logs for CLI and Docker image

core/src/helpers/index.ts, core/src/index.ts, core/test/unit/helpers.ts
=> Include ObjectId helpers in Core

cli/package-lock.json, core/src/database/database-connector.ts, core/src/index.ts
=> Fix MongoClient usage and default timeout in DB connector

examples/import-data-ts/example/package-lock.json, examples/import-data-ts/example/package.json, examples/import-data/example/helpers/index.js, examples/import-data/example/package-lock.json, examples/import-data/example/package.json
- Bump example packages
- Fix import in JS example
=> Fix JS data import example

cli/test/integration/index.ts, core/src/common/logger.ts, core/src/database/database-connector.ts, core/src/importer/index.ts, core/src/index.ts, core/src/populator/populator.ts, core/test/unit/log.ts
=> Restore CLI logging enabled by default

cli/.ci/script.sh, core/.ci/script.sh
=> Fix Codecov reporting

cli/package-lock.json, cli/package.json, core/package-lock.json, core/package.json, core/test/integration/index.ts, docker-image/test/tester/package-lock.json, docker-image/test/tester/package.json, examples/custom-docker-image/sample-data/package-lock.json, examples/custom-docker-image/sample-data/package.json, examples/import-data-ts/example/package-lock.json, examples/import-data-ts/example/package.json, examples/import-data/example/package-lock.json, package-lock.json, package.json
=> Update all dependencies

cli/src/index.ts, core/README.md, core/src/config.ts, core/test/integration/_importdata/populator-docs/array/array.cjs, core/test/integration/_importdata/populator-docs/object/object.cjs, core/test/integration/_importdata/populator-docs/object/object.js, core/test/integration/populator.ts, core/test/unit/config.ts, docs/import-data-definition.md
=> Support .cjs file extension by default

core/src/index.ts
=> Preserve stacktrace of internal error

examples/custom-docker-image/sample-data/helpers/index.js
=> Remove invalid export from docker example

cli/README.md
There was a typo in the cli README.
=> Fix typo in cli README

core/package-lock.json, core/package.json, core/src/populator/filesystem.ts, core/test/unit/FileSystem.ts
=> Disable require cache while loading other files than JSON

docker-image/dev.Dockerfile, docker-image/prod.Dockerfile, scripts/publish-npm-and-docker.sh
- Use Node 14 in base Docker image
- Fix release script
=> Use Node 14 in base Docker image

cli/src/index.ts, cli/test/integration/index.ts
=> Fix CLI exit behavior on error

lerna.json
- Introduce new category of pull request for changelog generation: "🔨 Maintenance"
- Update labels with emojis
=> Update changelog configuration

core/test/integration/index.ts
- Fix incorrect async/await usage when iterating over test collections
=> Fix unstable integration test

.github/workflows/branch.yaml, .github/workflows/pull-request.yaml
- Update Codecov uploader
- Update checkout and setup Node.js actions
- Update Node used to build the app on CI pipeline
=> Upgrade GitHub actions used in PR and branch pipelines

.gitignore, cli/package-lock.json, cli/package.json, cli/test/integration/index.ts, core/README.md, core/package-lock.json, core/package.json, core/src/config.ts, core/src/database/database-connector.ts, core/src/database/database.ts, core/src/importer/index.ts, core/src/index.ts, core/src/populator/filesystem.ts, core/src/populator/populator.ts, core/test/_helpers.ts, core/test/integration/index.ts, core/test/unit/database-connector.ts, core/test/unit/importer.ts, core/test/unit/transformer.ts, docker-image/.dockerignore, docker-image/dev.Dockerfile, docker-image/test/tester/package-lock.json, docker-image/test/tester/package.json, docker-image/test/tester/src/index.js, examples/custom-docker-image/sample-data/package-lock.json, examples/import-data-ts/example/package-lock.json, examples/import-data/example/package-lock.json, examples/mongoose-express/example/package-lock.json, package-lock.json, package.json
This PR changes API as the new MongoDB types are used for advanced configuration.
=> Update MongoDB driver to v5 and all other dependencies
